# Generated by Django 5.2 on 2025-04-23 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="sportskill",
            name="proficiency",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="favorite_sports",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="default_profile.png", upload_to="profile_pics"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Professional", "Professional"),
                ],
                default="Intermediate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sportskill",
            name="skill_level",
            field=models.CharField(default="Beginner", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="sportskill",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sport_skills",
                to="matcher.profile",
            ),
        ),
        migrations.AlterField(
            model_name="sportskill",
            name="sport",
            field=models.CharField(max_length=100),
        ),
    ]
